# Generated by Django 4.2.2 on 2023-07-12 19:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arrondissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_arrondissement",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nom de l'Arrondissement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_commune",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Nom de la Commune",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repondant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Status Infrastructure",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Status Infrastructure",
                    ),
                ),
                (
                    "qualite",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Status Infrastructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Status Infrastructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Type Infrastructure",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="webmapping.type",
                    ),
                ),
            ],
            options={
                "unique_together": {("type", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_secteur",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nom du Secteur",
                    ),
                ),
                (
                    "arrondissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmapping.arrondissement",
                        verbose_name="Nom de l'Arrondissement",
                    ),
                ),
            ],
            options={
                "unique_together": {("nom_secteur", "arrondissement")},
            },
        ),
        migrations.CreateModel(
            name="Quartier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_quartier",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Nom du Quartier",
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmapping.secteur",
                        verbose_name="Nom du Secteur",
                    ),
                ),
            ],
            options={
                "unique_together": {("nom_quartier", "secteur")},
            },
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Infrastructure",
                    ),
                ),
                (
                    "etat_voie",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="État de la voie",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Emplacement de l’infrastructure par rapport à la voie",
                    ),
                ),
                (
                    "cloture",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="État de la voie",
                    ),
                ),
                (
                    "accessibilite",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="État de la voie",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="État de la voie",
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "altitude",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Altitude"
                    ),
                ),
                (
                    "precision",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Precision"
                    ),
                ),
                (
                    "quartier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmapping.quartier",
                        verbose_name="Quartier de l'intrastructure",
                    ),
                ),
                (
                    "repondant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmapping.repondant",
                        verbose_name="Quartier de l'intrastructure",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmapping.status",
                        verbose_name="Status de  l'infrastructure",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webmapping.type",
                        verbose_name="Type d'infrastructure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="arrondissement",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webmapping.commune",
                verbose_name="Nom de la Commune",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="arrondissement",
            unique_together={("nom_arrondissement", "commune")},
        ),
    ]
