# Generated by Django 4.2.2 on 2023-07-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webmapping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="uploads_files/"),
                ),
            ],
        ),
    ]
