# Generated by Django 4.2.2 on 2023-08-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmapping', '0002_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='La taille de limage ne doit pas depassé 32x32 pixels.', upload_to='legend_images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmapping.type')),
            ],
        ),
    ]
