# Generated by Django 4.2.3 on 2023-07-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmapping', '0002_auto_20230709_2144'),
        ('webmapping', '0003_type'),
    ]

    operations = [
    ]
