# Generated by Django 4.2.3 on 2023-07-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmapping', '0004_merge_0002_auto_20230709_2144_0003_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type Infrastructure'),
        ),
    ]
