# Generated by Django 4.2.2 on 2023-08-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webmapping", "0005_alter_legend_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legend",
            options={"verbose_name": "Legende", "verbose_name_plural": "Legende"},
        ),
    ]
