# Generated by Django 4.2.3 on 2023-07-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmapping', '0005_alter_type_type_infrastructure'),
    ]

    operations = [
    ]
