# Generated by Django 4.2.3 on 2023-07-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmapping', '0007_alter_type_type'),
    ]

    operations = [
        
    ]
